### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by murphyl4** [aoliao12138/ReRF_Dataset#1]
I don't know how to prepare the data, such as how to make the mp4 file in the mask directory, and how to get bbox.json.
I have applied for access to your data but have not been granted permission.
I would be very grateful if you could tell me how to make the dataset myself.

**Comment by aoliao12138** [comment]
We apologize for the delay in granting access to our data. We released many permissions yesterday. If you have not yet received access, please provide us with your name, and we will investigate the matter further to ensure you get the necessary permissions.

To create the MP4 file in the mask directory, we utilize background matting to generate the mask video. You can refer to the [decode video](https://github.com/aoliao12138/ReRF/blob/master/data_util.py#L57) function in our ReRF repository to understand how to decode the mask video and place it into the mask directory.

As for obtaining the bbox.json file, we follow the approach used in DVGO. To illustrate, you can adjust the bounding box using their [vis_volume.py](https://github.com/sunset1995/DirectVoxGO#:~:text=Extention%20to%20new%20dataset) tool.

If you plan to create your own dataset, please note that ReRF supports multiview video sequences. The process typically involves capture, calibration, and segmentation. To get started, we would appreciate it if you could share some information about your capture system settings. This will enable us to provide more specific guidance tailored to your setup.

Thank you for your interest in our project. If you have any further questions or require additional support, please feel free to reach out. Thank you very much!
