### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by wunan9696** [aoliao12138/ReRF_Dataset#2]
Hi, we have applied for access to the data recently. Could you kindly grant us with the permission? Thanks!

**Comment by aoliao12138** [comment]
Hi,

Thank you for reaching out. Our team has responded to your inquiry via email. We are pleased to inform you that your data access request has been approved.

Should you have any further questions or require additional assistance, please do not hesitate to contact us.

**Comment by wunan9696** [comment]
Thanks!
